parameters:
    neo_start_interval: "P3D"
    neo_end_date: "now"

services:
    neo_data_fetcher:
        class: Neo\NasaBundle\Utils\NeoDataFetcher
        arguments: ["@guzzle.client", "%nasa.page%", "%nasa.api_key%", "%neo_start_interval%", "%neo_end_date%"]